const CONFIG={API_PREFIX:"/api/v1",API_ORIGIN:"https://longestformaiexplainervideogenerator.ai",POLL_MS:3000};
const $=id=>document.getElementById(id); let scenes=[],jobId=null,timer=null;
const apiBase=()=>{const q=new URLSearchParams(location.search).get("api");return (q||CONFIG.API_ORIGIN+CONFIG.API_PREFIX).replace(/\/$/,"")};
const words=t=>t.trim()?t.trim().split(/\s+/).length:0;
const esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
async function request(path,opt={}){const r=await fetch(apiBase()+path,{...opt,headers:{"Content-Type":"application/json","Accept":"application/json",...(opt.headers||{})}});const text=await r.text();let d={};try{d=JSON.parse(text)}catch{}if(!r.ok)throw Error(d.message||d.error||"API request failed ("+r.status+")");return d}
const FEATURES=[
"AI Explainer Video Generator","AI Image-to-Video Generator","AI Text-to-Video Generator","AI Video-to-Video Generator","AI Script-to-Video Generator","AI Storyboard Generator","AI Scene Generator","AI Shot Generator","AI Character Generator","AI Character Consistency","AI Style Transfer","AI Cinematic Video Generator","AI Documentary Generator","AI Featurette Generator","AI Trailer Generator","AI Short Film Generator","AI Long-Form Video Generator","AI Educational Video Generator","AI Presentation Video Generator","AI Product Video Generator","AI Marketing Video Generator","AI Social Video Generator","AI Avatar Video Generator","AI Voiceover Generator","AI Narration Generator","AI Dialogue Generator","AI Music Generator","AI Sound Effects Generator","AI Ambient Audio Generator","AI Audio Cleanup","AI All-in-One Sound Toggle","AI Subtitle Generator","AI Caption Generator","AI Translation","AI Dubbing","AI Lip Sync","AI Story Generator","AI Prompt Enhancer","AI Prompt-to-Storyboard","AI Image Generator","AI Image Editing","AI Background Generator","AI Poster Generator","AI Thumbnail Generator","AI Logo/Title Generator","AI B-Roll Generator","AI Motion Graphics","AI VFX Generator","AI Transition Generator","AI Color/Look Generator","AI Upscaling","AI Frame Interpolation","AI Video Restoration","AI Scene Continuity","AI Timeline Assembly","AI Multi-Scene Rendering","AI Batch Generation","AI Project Export","AI 360p Output","AI 480p Output","AI 720p Output","AI 1080p Output","AI 2160p (4K UHD) Output"];
$("featureGrid").innerHTML=FEATURES.map((x,i)=>"<article class='feature'><span>"+String(i+1).padStart(2,"0")+"</span><strong>"+x+"</strong><small>Available in the studio architecture</small></article>").join("");
function plan(){const t=$("script").value.trim();if(!t){$("projectStatus").textContent="Add a prompt or script first";return false}const target=Math.max(5,Number($("sceneLength").value)||30);const chunks=t.split(/(?<=[.!?])\s+/).filter(Boolean);scenes=[];let cur="";for(const s of chunks){if(cur&&cur.split(/\s+/).length>=target*2){scenes.push(cur);cur=""}cur+=(cur?" ":"")+s}if(cur)scenes.push(cur);$("projectStatus").textContent="Planned "+scenes.length+" scenes";$("queue").className="queue";$("queue").innerHTML=scenes.map((s,i)=>"<article class='scene'><strong>Scene "+(i+1)+"</strong><p>"+esc(s)+"</p></article>").join("");return true}
async function health(){ $("apiStatus").textContent="API status: checking…";try{const d=await request("/health");$("apiStatus").textContent="API status: online"+(d.version?" · "+d.version:"")}catch(e){$("apiStatus").textContent="API status: unavailable · "+e.message}}
async function generate(){if(!plan())return;$("generationStatus").textContent="Submitting…";try{const d=await request("/projects",{method:"POST",body:JSON.stringify({title:$("title").value,script:$("script").value,scenes,resolution:$("resolution").value,sound:$("sound").value==="On",durationMode:$("durationMode").value})});const id=d.id||d.projectId;if(!id)throw Error("API did not return a project id");const j=await request("/projects/"+encodeURIComponent(id)+"/agent",{method:"POST",body:JSON.stringify({mode:"long-form-ai-video",sceneIds:scenes.map((_,i)=>i+1),resolution:$("resolution").value,sound:$("sound").value==="On"})});jobId=j.jobId||j.id;if(!jobId)throw Error("API did not return a job id");$("generationStatus").textContent="Job "+jobId;poll();if(timer)clearInterval(timer);timer=setInterval(poll,CONFIG.POLL_MS)}catch(e){$("generationStatus").textContent="Generation unavailable";$("agentLog").textContent=e.message}}
async function poll(){if(!jobId)return;try{const d=await request("/jobs/"+encodeURIComponent(jobId));const p=Math.max(0,Math.min(100,Number(d.progress||0)));$("progressBar").style.width=p+"%";$("jobCard").innerHTML="<strong>"+esc(d.stage||d.status||"Processing")+"</strong><span>"+esc(d.message||"Backend job is running.")+"</span>";$("agentLog").textContent=JSON.stringify(d,null,2);if(["completed","failed","cancelled"].includes(String(d.status).toLowerCase())){clearInterval(timer);timer=null}}catch(e){$("agentLog").textContent=e.message}}
$("health").onclick=health;$("planButton").onclick=plan;$("generateButton").onclick=generate;
$("download").onclick=()=>{const p={schemaVersion:3,title:$("title").value,prompt:$("script").value,resolution:$("resolution").value,sound:$("sound").value,durationMode:$("durationMode").value,scenes,features:FEATURES};const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(p,null,2)],{type:"application/json"}));a.download="longest-form-ai-video-project.json";a.click();URL.revokeObjectURL(a.href)};