const CONFIG={APP_ORIGIN:"https://longestformaiexplainervideogenerator.ai",API_PREFIX:"/api/v1",POLL_MS:3000};const $=id=>document.getElementById(id);let scenes=[],projectId=null,jobId=null,timer=null;
const apiBase=()=>{const o=new URLSearchParams(location.search).get("api");if(o)return o.replace(/\/$/,"");return CONFIG.APP_ORIGIN+CONFIG.API_PREFIX};
const words=t=>t.trim()?t.trim().split(/\s+/).length:0;const time=x=>{x=Math.max(0,Math.round(x));const h=Math.floor(x/3600),m=Math.floor(x%3600/60),s=x%60;return h?h+":"+String(m).padStart(2,"0")+":"+String(s).padStart(2,"0"):m+":"+String(s).padStart(2,"0")};const esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const status=(id,t)=>$(id).textContent=t;async function request(path,opt={}){const r=await fetch(apiBase()+path,{...opt,headers:{"Content-Type":"application/json",...(opt.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.message||d.error||"API request failed ("+r.status+")");return d}
function stats(){const n=words($("script").value),w=Number($("wpm").value)||150;$("wordCount").textContent=n.toLocaleString();$("duration").textContent=time(n/w*60)}
function split(t,target,wpm){const a=t.trim().split(/(?<=[.!?])\s+/).filter(Boolean),lim=Math.max(10,Math.round(target*wpm/60)),out=[];let cur=[],n=0;for(const s of a){const k=words(s);if(cur.length&&n+k>lim){out.push(cur.join(" "));cur=[];n=0}cur.push(s);n+=k}if(cur.length)out.push(cur.join(" "));return out}
function render(){const q=$("queue");$("sceneCount").textContent=scenes.length;if(!scenes.length){q.className="queue empty";q.textContent="Add a script and plan scenes to begin.";return}q.className="queue";q.innerHTML=scenes.map((s,i)=>"<article class='scene'><div class='scene-head'><strong>Scene "+(i+1)+"</strong><span class='badge'>Planned</span></div><p>"+esc(s)+"</p></article>").join("")}
function plan(){const t=$("script").value.trim();if(!t){status("planStatus","Add a script first");return false}scenes=split(t,Number($("sceneLength").value)||30,Number($("wpm").value)||150);status("planStatus","Planned "+scenes.length+" scenes");render();return true}
async function createProject(){if(!plan())return;status("planStatus","Creating project…");try{const d=await request("/projects",{method:"POST",body:JSON.stringify({title:$("title").value,script:$("script").value,wordsPerMinute:Number($("wpm").value)||150,sceneTargetSeconds:Number($("sceneLength").value)||30,scenes})});projectId=d.id||d.projectId;status("planStatus","Project "+projectId+" ready");status("agentStatus","Project ready for agent")}catch(e){status("planStatus",e.message)}}
async function startAgent(){if(!projectId){await createProject();if(!projectId)return}status("agentStatus","Starting agent…");$("agentLog").textContent="Submitting project plan to the production agent…";try{const d=await request("/projects/"+encodeURIComponent(projectId)+"/agent",{method:"POST",body:JSON.stringify({mode:"long-form-explainer",sceneIds:scenes.map((_,i)=>i+1)})});jobId=d.jobId||d.id;status("agentStatus","Agent job "+jobId);$("cancelButton").disabled=false;startPolling()}catch(e){status("agentStatus",e.message);$("agentLog").textContent=e.message}}
async function poll(){if(!jobId)return;try{const d=await request("/jobs/"+encodeURIComponent(jobId));const p=Math.max(0,Math.min(100,Number(d.progress??0)));$("progressBar").style.width=p+"%";status("generationStatus",d.status||p+"%");$("jobCard").innerHTML="<strong>"+esc(d.stage||d.status||"Processing")+"</strong><span>"+esc(d.message||"Server-side generation is in progress.")+"</span>";$("agentLog").textContent=JSON.stringify(d,null,2);if(["completed","failed","cancelled"].includes(String(d.status).toLowerCase())){clearInterval(timer);timer=null;$("cancelButton").disabled=true;$("refreshJob").disabled=false;if(String(d.status).toLowerCase()==="completed")$("outputButton").disabled=false}}catch(e){status("generationStatus",e.message)}}
function startPolling(){if(timer)clearInterval(timer);poll();timer=setInterval(poll,CONFIG.POLL_MS)}
$("script").addEventListener("input",stats);$("wpm").addEventListener("input",stats);$("planButton").onclick=plan;$("saveProject").onclick=createProject;$("agentButton").onclick=startAgent;$("refreshJob").onclick=poll;
$("cancelButton").onclick=async()=>{if(!jobId)return;try{await request("/jobs/"+encodeURIComponent(jobId)+"/cancel",{method:"POST"});await poll()}catch(e){status("generationStatus",e.message)}};
$("outputButton").onclick=async()=>{if(!projectId)return;try{const d=await request("/projects/"+encodeURIComponent(projectId)+"/output");if(d.url)location.href=d.url;else status("generationStatus","Output is not ready.")}catch(e){status("generationStatus",e.message)}};
$("download").onclick=()=>{const p={schemaVersion:2,title:$("title").value,script:$("script").value,wordsPerMinute:Number($("wpm").value)||150,sceneTargetSeconds:Number($("sceneLength").value)||30,scenes,durationSeconds:words($("script").value)/(Number($("wpm").value)||150)*60};const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(p,null,2)],{type:"application/json"}));a.download="explainer-video-project.json";a.click();URL.revokeObjectURL(a.href)};
$("health").onclick=async()=>{status("apiStatus","Checking…");try{const d=await request("/health");status("apiStatus","API online"+(d.version?" · "+d.version:""))}catch(e){status("apiStatus","API unavailable · "+e.message)}};stats();render();